baseURL = "https://www.example.com"
languageCode = "en-us"
title = "prasanthabr"
theme = "hugo-digital-garden-theme"
themesdir = "themes"
copyright = "prasanth"


[params]
  name = "Heres a valiant attempt to collate what makes me tick. To remind my future self on what had inspired in the past."
  description = "Random thoughts and unfinished rants."
  initials = "PMA"
  googleAnalytics = ""

  [[params.social]]
    name = "Twitter"
    link = "https://twitter.com/prasanthabr"
    icon = "fab fa-twitter"

  [[params.social]]
    name = "Github"
    link = "https://github.com/prasanthabr"
    icon = "fab fa-github"

  [[params.social]]
    name = "LinkedIn"
    link = "https://www.linkedin.com/in/pabra/"
    icon = "fab fa-linkedin-in"

  [[params.social]]
    name = "Mastodon"
    link = "https://mastodon.social/@prasanthabr"
    icon = "fab fa-mastodon"


[menu]
  [[menu.main]]
    name = "Writing"
    url = "/long-form/"
    weight = 1
  [[menu.main]]
    name = "Zettelkasten"
    url = "/zettel/"
    weight = 2
  [[menu.main]]
    name = "Projects"
    url = "/projects/"
    weight = 3
  [[menu.main]]
    name = "Bookmarks"
    url = "/bookmarks/"
    weight = 4
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 5


[taxonomies]
  zettel_tags = 'zettel_tags'
  project_tags = 'project_tags'
  bookmark_tags = 'bookmark_tags'
  longform_tags = 'longfrom_tags'


[markup]
  defaultMarkdownHandler = 'goldmark'
  [markup.goldmark.renderer]
    unsafe = true
  [markup.goldmark.extensions]
    definitionList = true
    footnote = true
    linkify = true
    strikethrough = true
    table = true
    taskList = true
    typographer = true
  [markup.highlight]
    # Choose from https://xyproto.github.io/splash/docs/all.html
    style = 'monokailight'
